### ISSUE TITLE
Class "Js" not found

### ISSUE THREAD

**Issue by atmonshi** [RVxLab/filament-colorpicker#10]
Laravel: 8
php 8.0
filament: 2.0
filament-colorpicker: 1.2

after installing the package and adding
`\RVxLab\FilamentColorPicker\Forms\ColorPicker::make('color'),`

to my resource
I am getting the error:

```
Class "Js" not found (View: vendor/rvxlab/filament-colorpicker/resources/views/colorpicker.blade.php)
```

**Comment by RVxLab** [comment]
You're probably using Laravel 8.69 or before, which doesn't have this class.

This is also incorrectly specified in the composer.json of this package, fix incoming.

**Comment by atmonshi** [comment]
thanks for the reply.
still after the update the same issue, it helps to set it with full path as:
`\Illuminate\Support\Js::from($getPickerOptions())`

thanks again 🙏🏽

**Comment by RVxLab** [comment]
Ah I see, you don't use the aliases. I shouldn't have assumed that, I'll fix that as well.

Keep an eye out for 1.2.1 which will address this.
