### ISSUE TITLE
Sometimes the picker is not displaying the color platte

### ISSUE THREAD

**Issue by mohamedmoussasoli** [RVxLab/filament-colorpicker#19]
<img width="349" alt="Screenshot 2022-04-07 at 3 24 24 PM" src="https://user-images.githubusercontent.com/9276573/162209328-e3e8aa4d-f30e-4d9a-abec-a8767ceb7e44.png">

**Comment by RVxLab** [comment]
Can you send me the console output? I have a hunch this is a CSP issue.

**Comment by mohamedmoussasoli** [comment]
Here is my console output when clicking in the picker

<img width="1279" alt="Screenshot 2022-04-07 at 4 06 52 PM" src="https://user-images.githubusercontent.com/9276573/162218309-6267e1dc-4634-4bfa-b9f6-cad6fc82c8c5.png">

**Comment by mohamedmoussasoli** [comment]
Ok i will try to make and new repo with an example.

i have another question. is there a way to clear the selected color.

Thanks.

**Comment by RVxLab** [comment]
Not at this time, see #18.

**Comment by RVxLab** [comment]
The ability to clear the selected colour has been added in 1.4.0.

**Comment by RVxLab** [comment]
Have you been able to reproduce this? If not I’ll close this.

**Comment by mohamedmoussasoli** [comment]
It tried it in safari and works fine, but not in google chrome

**Comment by RVxLab** [comment]
As of version Filament v2.10.45 there is a built-in colour picker. As this is a core built-in and serves the exact same purpose as this package I recommend switching to that.
